"""dtq_core: shared models, Redis key layout, and typed errors."""

from dtq_core.errors import (
    DtqError,
    IdempotencyInProgressError,
    InvalidTaskError,
    PayloadTooLargeError,
    QueueFullError,
    RedisUnavailableError,
    TaskCancelledError,
    TaskRetryExhaustedError,
    TaskTimeoutError,
    UnknownTaskTypeError,
    WorkerUnavailableError,
)
from dtq_core.keys import (
    AUDIT_STREAM,
    CANCELLED_SET,
    CONSUMER_GROUP,
    DLQ_STREAM,
    EVENTS_CHANNEL,
    RECENT_ZSET,
    RETRY_CLAIMED,
    RETRY_SCHEDULE,
    SCHEDULER_LOCK,
    WORKERS_SET,
    pause_key,
    priority_streams,
    stream_name,
    task_key,
    worker_key,
)
from dtq_core.models import (
    VALID_TRANSITIONS,
    InvalidTransition,
    Task,
    TaskStatus,
    is_terminal,
    transition,
)

__all__ = [
    "AUDIT_STREAM",
    "CANCELLED_SET",
    "CONSUMER_GROUP",
    "DLQ_STREAM",
    "EVENTS_CHANNEL",
    "RECENT_ZSET",
    "RETRY_CLAIMED",
    "RETRY_SCHEDULE",
    "SCHEDULER_LOCK",
    "VALID_TRANSITIONS",
    "WORKERS_SET",
    "DtqError",
    "IdempotencyInProgressError",
    "InvalidTaskError",
    "InvalidTransition",
    "PayloadTooLargeError",
    "QueueFullError",
    "RedisUnavailableError",
    "Task",
    "TaskCancelledError",
    "TaskRetryExhaustedError",
    "TaskStatus",
    "TaskTimeoutError",
    "UnknownTaskTypeError",
    "WorkerUnavailableError",
    "is_terminal",
    "pause_key",
    "priority_streams",
    "stream_name",
    "task_key",
    "transition",
    "worker_key",
]
